version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: kamerinos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Colombia2026*
      POSTGRES_DB: kamerinos_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kamerinos_net

  redis:
    image: redis:7-alpine
    container_name: kamerinos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kamerinos_net

volumes:
  pg_data:
  redis_data:

networks:
  kamerinos_net:
    driver: bridge
