import { ForbiddenException } from '@nestjs/common';
import { TurnRole, TurnTokenPayload } from './interfaces/turn-token-payload';

/** Subject of an operation, always resolved from the verified turn token. */
export interface TurnSubject {
  userId: string;
  role?: TurnRole;
}

/**
 * ADR 0012 (identity of the write tools), points 1 and 2: the subject of a write
 * operation comes from the turn token — never from the body, the query or an
 * argument generated by the model — and a turn without a verified user cannot
 * write (anonymous channel). There is an architectural test
 * (`__tests__/internal-identity-contract.spec.ts`) that fails if an internal
 * handler takes identity from the body or the query.
 *
 * Usage of the ready mechanism in the first Phase 2 endpoint that needs identity:
 *
 * ```ts
 * @Post('me/bookings')
 * create(@TurnContext() turn: TurnTokenPayload, @Body() dto: CreateBookingRequest) {
 *   const subject = requireTurnUser(turn); // 403 when the turn is anonymous
 *   return this.bookingsService.create(subject.userId, dto);
 * }
 * ```
 *
 * The `Idempotency-Key` of that write travels in its own header (ADR 0008); see
 * the bookings endpoint for the honoured contract.
 */
export function requireTurnUser(turn: TurnTokenPayload | undefined): TurnSubject {
  if (!turn?.userId) {
    throw new ForbiddenException(
      'El turno no tiene usuario identificado: las escrituras necesitan identidad verificada en el turn token',
    );
  }

  return { userId: turn.userId, role: turn.role };
}
